export default {
  // example colors with dark mode
  colors: {
    text: "#282828",
    background: "#fff",
    primary: "#07c",
    modes: {
      dark: {
        text: "#fff",
        background: "#000",
        primary: "#0cf",
      },
    },
  },
  fonts: {
    body: "system-ui, sans-serif",
    heading: "Georgia, serif",
    monospace: "Menlo, monospace",
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64],
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  letterSpacings: {
    body: "normal",
    caps: "0.2em",
  },
  buttons: {
    primary: {
      color: "#282828",
      position: "relative",
      paddingX: 32,
      paddingY: 10,
      zIndex: 1,
      background: "none",
      fontWeight: "bold",
      fontSize: "1.175em",
      borderWidth: "initial",
      borderStyle: "none",
      borderColor: "initial",
      borderImage: "initial",
      "::before": {
        content: '""',
        position: "absolute",
        width: "calc(100% + 3px)",
        height: "calc(100% + 3px)",
        top: "0.45em",
        left: "0.45em",
        backgroundColor: "#839eb5",
        zIndex: -1,
        transition: "0.15s ease-out",
      },
      ":hover:before": {
        top: 0,
        left: 0,
      },
      "::after": {
        content: '""',
        position: "absolute",
        top: 0,
        left: 0,
        width: 100 + "%",
        height: 100 + "%",
        border: "solid 3px #282828",
        cursor: "pointer",
      },
    },
    secondary: {
      color: "#282828",
      position: "relative",
      paddingX: 32,
      paddingY: 10,
      zIndex: 1,
      background: "none",
      fontWeight: "bold",
      fontSize: "1.175em",
      borderWidth: "initial",
      borderStyle: "none",
      borderColor: "initial",
      borderImage: "initial",
      "::before": {
        content: '""',
        position: "absolute",
        width: "calc(100% + 3px)",
        height: "calc(100% + 3px)",
        top: "0.45em",
        left: "0.45em",
        backgroundColor: "#ffc700",
        zIndex: -1,
        transition: "0.15s ease-out",
      },
      ":hover:before": {
        top: 0,
        left: 0,
      },
      "::after": {
        content: '""',
        position: "absolute",
        top: 0,
        left: 0,
        width: 100 + "%",
        height: 100 + "%",
        border: "solid 3px #282828",
        cursor: "pointer",
      },
    },
  },
}
